require("hristochavez.plugins.kanagawa")
require("hristochavez.plugins-setup")
require("hristochavez.plugins.lualine")
require("hristochavez.plugins.nvim_web_devicons")
require("hristochavez.plugins.auto_save")
require("hristochavez.plugins.comment")
require("hristochavez.plugins.nvim_tree")
require("hristochavez.plugins.telescope")
require("hristochavez.plugins.nvim_cmp")
require("hristochavez.plugins.lsp.mason")
require("hristochavez.plugins.lsp.lspsaga")
require("hristochavez.plugins.lsp.lspconfig")
require("hristochavez.core.keymaps")
require("hristochavez.core.colorscheme")
require("hristochavez.core.options")

